### ISSUE TITLE
GET queries don't allow simple strings as params

### ISSUE THREAD

**Issue by Sco768** [lestrrat/JSON-RPC#10]
Hello,
ran into a small problem with no params being passed with GET, removed eval to see the problem:

```
curl -g -6  'http://[::]:9080/hg?id=1&params="Hola"&method=guess'
{"error":{"code":-32600,"message":"JSON text must be an object or array (but found number, string, true, false or null, use allow_nonref to allow this) at /usr/share/perl5/JSON/RPC/Parser.pm line 64.\n"}}
```
(disregard the line number)

I believe changing line 74 of JSON/RPC/Parser.pm (in construct_from_get_req) to
`        $decoded_params = eval { $self->coder->allow_nonref->decode( $params->{params} ) };`
solves the problem.

**Comment by lestrrat** [comment]
PRs welcome!

**Comment by Sco768** [comment]
#11
